{{- if .Values.basicAuth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quine-enterprise.fullname" . }}-credentials
type: Opaque
data:
  htpasswd: {{ .Values.basicAuth.htpasswd | b64enc }}
{{- end }}