{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "quine-enterprise.fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  labels:
    {{- include "quine-enterprise.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
  - hosts:
    - quine-enterprise.local
    secretName: {{ include "quine-enterprise.fullname" . }}-tls-secret
  rules:
  - host: quine-enterprise.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ include "quine-enterprise.fullname" . }}
            port: 
              number: {{ .Values.service.port }}
{{- end }}