{{- if .Values.metrics.prometheus.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "quine-enterprise.fullname" . }}-prometheus-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "quine-enterprise.fullname" . }}-prometheus-role
rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
      - endpoints
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "quine-enterprise.fullname" . }}-prometheus-role-binding
subjects:
  - kind: ServiceAccount
    name: {{ include "quine-enterprise.fullname" . }}-prometheus-sa
roleRef:
  kind: Role
  name: {{ include "quine-enterprise.fullname" . }}-prometheus-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}