apiVersion: v1
kind: Service
metadata:
  name: {{ include "quine-enterprise.fullname" . }}
  labels:
    {{- include "quine-enterprise.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
    {{- include "quine-enterprise.prometheusServicePort" . | nindent 4 }}
  selector:
    {{- include "quine-enterprise.selectorLabels" . | nindent 4 }}
