apiVersion: v1
kind: Service
metadata:
  name: {{ include "novelty.fullname" . }}
  labels:
    {{- include "novelty.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: {{ .Values.service.name }}
  selector:
    {{- include "novelty.selectorLabels" . | nindent 4 }}
