{
 "title": "Quine",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "SHOW TAG VALUES WITH KEY = \"member_id\" "
   },
   {
    "name": "ingest",
    "query": "SHOW MEASUREMENTS WITH MEASUREMENT =~ /ingest.*.(bytes|count)/"
   },
   {
    "name": "standing_query",
    "query": "SHOW MEASUREMENTS WITH MEASUREMENT =~ /standing-queries.*/"
   }
  ]
 },
 "panels": [
  {
   "title": "Standing Query Results",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "member_id" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "/^$standing_query$/",
     "select": [
      [
       { "params": [ "one-minute" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "member_id", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Overall Ingest Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "SELECT SUM(\"ingested\") FROM (SELECT mean(\"one-minute\") AS \"ingested\" FROM \"$ingest\" WHERE (\"member_id\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"member_id\"  fill(linear)) GROUP BY time($__interval) fill(linear)"
    }
   ]
  },
  {
   "title": "Ingest Rate Per Host",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "member_id" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "ingest.g1g2.count",
     "query": "SELECT mean(\"one-minute\") FROM \"$ingest\" WHERE (\"member_id\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"member_id\" fill(linear)",
     "select": [
      [
       { "params": [ "one-minute" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "member_id", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Cassandra Latency (95th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "member_id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "s0.cql-requests",
     "select": [
      [
       { "params": [ "95-percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "member_id", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}