
admin:
  existingSecret: grafana-admin-credentials

datasources:
 datasources.yaml:
   apiVersion: 1
   datasources:
      # <string, required> name of the datasource. Required
    - name: Streaming Graph Metrics (InfluxDB)
      # <string, required> datasource type. Required
      type: influxdb
      # <string, required> access mode. proxy or direct (Server or Browser in the UI). Required
      access: proxy
      # <int> org id. will default to orgId 1 if not specified
      orgId: 1
      # <string> url
      url: http://influx-influxdb:8086
      # <string> database name, if used
      database: metrics
      # <bool> enable/disable with credentials headers
      withCredentials: false
      # <bool> mark as default datasource. Max one per org
      isDefault: true
      # <map> fields that will be converted to json and stored in json_data
      jsonData:
         httpMode: "GET"
      version: 1
      # <bool> allow users to edit datasources from the UI.
      editable: false

dashboardProviders:
   dashboardproviders.yaml:
     apiVersion: 1
     providers:
     - name: 'default'
       orgId: 1
       folder: ''
       type: file
       disableDeletion: false
       editable: true
       options:
         path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    quine-dashboard:
      json: |
        {
          "annotations": {
            "list": [
              {
                "builtIn": 1,
                "datasource": "-- Grafana --",
                "enable": true,
                "hide": true,
                "iconColor": "rgba(0, 211, 255, 1)",
                "name": "Annotations & Alerts",
                "target": {
                  "limit": 100,
                  "matchAny": false,
                  "tags": [],
                  "type": "dashboard"
                },
                "type": "dashboard"
              }
            ]
          },
          "editable": true,
          "fiscalYearStartMonth": 0,
          "graphTooltip": 0,
          "id": 1,
          "iteration": 1641499698043,
          "links": [],
          "liveNow": false,
          "panels": [
            {
              "fieldConfig": {
                "defaults": {
                  "color": {
                    "mode": "palette-classic"
                  },
                  "custom": {
                    "axisLabel": "results / s",
                    "axisPlacement": "auto",
                    "axisSoftMin": 0,
                    "barAlignment": 0,
                    "drawStyle": "line",
                    "fillOpacity": 0,
                    "gradientMode": "none",
                    "hideFrom": {
                      "legend": false,
                      "tooltip": false,
                      "viz": false
                    },
                    "lineInterpolation": "linear",
                    "lineStyle": {
                      "fill": "solid"
                    },
                    "lineWidth": 1,
                    "pointSize": 5,
                    "scaleDistribution": {
                      "type": "linear"
                    },
                    "showPoints": "auto",
                    "spanNulls": false,
                    "stacking": {
                      "group": "A",
                      "mode": "none"
                    },
                    "thresholdsStyle": {
                      "mode": "off"
                    }
                  },
                  "mappings": [],
                  "thresholds": {
                    "mode": "absolute",
                    "steps": [
                      {
                        "color": "green",
                        "value": null
                      },
                      {
                        "color": "red",
                        "value": 80
                      }
                    ]
                  }
                },
                "overrides": []
              },
              "gridPos": {
                "h": 9,
                "w": 24,
                "x": 0,
                "y": 0
              },
              "id": 6,
              "options": {
                "legend": {
                  "calcs": [],
                  "displayMode": "list",
                  "placement": "bottom"
                },
                "tooltip": {
                  "mode": "single"
                }
              },
              "targets": [
                {
                  "groupBy": [
                    {
                      "params": [
                        "$__interval"
                      ],
                      "type": "time"
                    },
                    {
                      "params": [
                        "member_id"
                      ],
                      "type": "tag"
                    },
                    {
                      "params": [
                        "linear"
                      ],
                      "type": "fill"
                    }
                  ],
                  "measurement": "/^$standing_query$/",
                  "orderByTime": "ASC",
                  "policy": "default",
                  "refId": "A",
                  "resultFormat": "time_series",
                  "select": [
                    [
                      {
                        "params": [
                          "one-minute"
                        ],
                        "type": "field"
                      },
                      {
                        "params": [],
                        "type": "mean"
                      }
                    ]
                  ],
                  "tags": [
                    {
                      "key": "member_id",
                      "operator": "=~",
                      "value": "/^$host$/"
                    }
                  ]
                }
              ],
              "title": "Standing Query Results",
              "type": "timeseries"
            },
            {
              "fieldConfig": {
                "defaults": {
                  "color": {
                    "mode": "palette-classic"
                  },
                  "custom": {
                    "axisLabel": "records / s",
                    "axisPlacement": "auto",
                    "barAlignment": 0,
                    "drawStyle": "line",
                    "fillOpacity": 0,
                    "gradientMode": "none",
                    "hideFrom": {
                      "legend": false,
                      "tooltip": false,
                      "viz": false
                    },
                    "lineInterpolation": "linear",
                    "lineWidth": 3,
                    "pointSize": 5,
                    "scaleDistribution": {
                      "type": "linear"
                    },
                    "showPoints": "auto",
                    "spanNulls": false,
                    "stacking": {
                      "group": "A",
                      "mode": "none"
                    },
                    "thresholdsStyle": {
                      "mode": "off"
                    }
                  },
                  "mappings": [],
                  "thresholds": {
                    "mode": "absolute",
                    "steps": [
                      {
                        "color": "green",
                        "value": null
                      },
                      {
                        "color": "red",
                        "value": 80
                      }
                    ]
                  }
                },
                "overrides": []
              },
              "gridPos": {
                "h": 8,
                "w": 24,
                "x": 0,
                "y": 9
              },
              "id": 8,
              "interval": "20s",
              "options": {
                "legend": {
                  "calcs": [],
                  "displayMode": "list",
                  "placement": "bottom"
                },
                "tooltip": {
                  "mode": "single"
                }
              },
              "targets": [
                {
                  "query": "SELECT SUM(\"ingested\") FROM (SELECT mean(\"one-minute\") AS \"ingested\" FROM \"$ingest\" WHERE (\"member_id\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"member_id\"  fill(linear)) GROUP BY time($__interval) fill(linear)",
                  "rawQuery": true,
                  "refId": "A",
                  "resultFormat": "time_series"
                }
              ],
              "title": "Overall Ingest Rate",
              "type": "timeseries"
            },
            {
              "fieldConfig": {
                "defaults": {
                  "color": {
                    "mode": "palette-classic"
                  },
                  "custom": {
                    "axisLabel": "records / s",
                    "axisPlacement": "auto",
                    "axisSoftMin": 0,
                    "barAlignment": 0,
                    "drawStyle": "line",
                    "fillOpacity": 0,
                    "gradientMode": "none",
                    "hideFrom": {
                      "legend": false,
                      "tooltip": false,
                      "viz": false
                    },
                    "lineInterpolation": "linear",
                    "lineWidth": 1,
                    "pointSize": 2,
                    "scaleDistribution": {
                      "type": "linear"
                    },
                    "showPoints": "auto",
                    "spanNulls": false,
                    "stacking": {
                      "group": "A",
                      "mode": "none"
                    },
                    "thresholdsStyle": {
                      "mode": "off"
                    }
                  },
                  "mappings": [],
                  "thresholds": {
                    "mode": "absolute",
                    "steps": [
                      {
                        "color": "green",
                        "value": null
                      },
                      {
                        "color": "red",
                        "value": 80
                      }
                    ]
                  }
                },
                "overrides": []
              },
              "gridPos": {
                "h": 12,
                "w": 24,
                "x": 0,
                "y": 17
              },
              "id": 4,
              "interval": "60s",
              "options": {
                "legend": {
                  "calcs": [],
                  "displayMode": "list",
                  "placement": "bottom"
                },
                "tooltip": {
                  "mode": "single"
                }
              },
              "targets": [
                {
                  "groupBy": [
                    {
                      "params": [
                        "$__interval"
                      ],
                      "type": "time"
                    },
                    {
                      "params": [
                        "member_id"
                      ],
                      "type": "tag"
                    },
                    {
                      "params": [
                        "linear"
                      ],
                      "type": "fill"
                    }
                  ],
                  "measurement": "ingest.g1g2.count",
                  "orderByTime": "ASC",
                  "policy": "default",
                  "query": "SELECT mean(\"one-minute\") FROM \"$ingest\" WHERE (\"member_id\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"member_id\" fill(linear)",
                  "rawQuery": true,
                  "refId": "A",
                  "resultFormat": "time_series",
                  "select": [
                    [
                      {
                        "params": [
                          "one-minute"
                        ],
                        "type": "field"
                      },
                      {
                        "params": [],
                        "type": "mean"
                      }
                    ]
                  ],
                  "tags": [
                    {
                      "key": "member_id",
                      "operator": "=~",
                      "value": "/^$host$/"
                    }
                  ]
                }
              ],
              "title": "Ingest Rate Per Host",
              "type": "timeseries"
            },
            {
              "fieldConfig": {
                "defaults": {
                  "color": {
                    "mode": "palette-classic"
                  },
                  "custom": {
                    "axisLabel": "ms",
                    "axisPlacement": "auto",
                    "barAlignment": 0,
                    "drawStyle": "line",
                    "fillOpacity": 0,
                    "gradientMode": "none",
                    "hideFrom": {
                      "legend": false,
                      "tooltip": false,
                      "viz": false
                    },
                    "lineInterpolation": "linear",
                    "lineWidth": 1,
                    "pointSize": 5,
                    "scaleDistribution": {
                      "type": "linear"
                    },
                    "showPoints": "auto",
                    "spanNulls": false,
                    "stacking": {
                      "group": "A",
                      "mode": "none"
                    },
                    "thresholdsStyle": {
                      "mode": "off"
                    }
                  },
                  "mappings": [],
                  "thresholds": {
                    "mode": "absolute",
                    "steps": [
                      {
                        "color": "green",
                        "value": null
                      },
                      {
                        "color": "red",
                        "value": 80
                      }
                    ]
                  }
                }
              },
              "gridPos": {
                "h": 9,
                "w": 24,
                "x": 0,
                "y": 29
              },
              "id": 2,
              "options": {
                "legend": {
                  "calcs": [],
                  "displayMode": "list",
                  "placement": "bottom"
                },
                "tooltip": {
                  "mode": "single"
                }
              },
              "targets": [
                {
                  "groupBy": [
                    {
                      "params": [
                        "$__interval"
                      ],
                      "type": "time"
                    },
                    {
                      "params": [
                        "member_id"
                      ],
                      "type": "tag"
                    },
                    {
                      "params": [
                        "null"
                      ],
                      "type": "fill"
                    }
                  ],
                  "measurement": "s0.cql-requests",
                  "orderByTime": "ASC",
                  "policy": "default",
                  "refId": "A",
                  "resultFormat": "time_series",
                  "select": [
                    [
                      {
                        "params": [
                          "95-percentile"
                        ],
                        "type": "field"
                      },
                      {
                        "params": [],
                        "type": "mean"
                      }
                    ]
                  ],
                  "tags": [
                    {
                      "key": "member_id",
                      "operator": "=~",
                      "value": "/^$host$/"
                    }
                  ]
                }
              ],
              "title": "Cassandra Latency (95th percentile)",
              "type": "timeseries"
            }
          ],
          "refresh": "5s",
          "schemaVersion": 33,
          "style": "dark",
          "tags": [],
          "templating": {
            "list": [
              {
                "current": {
                  "selected": true,
                  "text": [
                    "All"
                  ],
                  "value": [
                    "$__all"
                  ]
                },
                "definition": "SHOW TAG VALUES WITH KEY = \"member_id\" ",
                "hide": 0,
                "includeAll": true,
                "multi": true,
                "name": "host",
                "options": [],
                "query": "SHOW TAG VALUES WITH KEY = \"member_id\" ",
                "refresh": 1,
                "regex": "",
                "skipUrlSync": false,
                "sort": 0,
                "type": "query"
              },
              {
                "current": {
                  "selected": false,
                  "text": "None",
                  "value": ""
                },
                "definition": "SHOW MEASUREMENTS WITH MEASUREMENT =~ /ingest.*.(bytes|count)/",
                "hide": 0,
                "includeAll": false,
                "multi": false,
                "name": "ingest",
                "options": [],
                "query": "SHOW MEASUREMENTS WITH MEASUREMENT =~ /ingest.*.(bytes|count)/",
                "refresh": 2,
                "regex": "",
                "skipUrlSync": false,
                "sort": 0,
                "type": "query"
              },
              {
                "current": {
                  "selected": false,
                  "text": "None",
                  "value": ""
                },
                "definition": "SHOW MEASUREMENTS WITH MEASUREMENT =~ /standing-queries.*/",
                "hide": 0,
                "includeAll": false,
                "multi": false,
                "name": "standing_query",
                "options": [],
                "query": "SHOW MEASUREMENTS WITH MEASUREMENT =~ /standing-queries.*/",
                "refresh": 1,
                "regex": "",
                "skipUrlSync": false,
                "sort": 0,
                "type": "query"
              }
            ]
          },
          "time": {
            "from": "now-15m",
            "to": "now"
          },
          "timepicker": {},
          "timezone": "",
          "title": "Quine",
          "uid": "H5_D32Vnz",
          "version": 4,
          "weekStart": ""
        }

